name: socketnotifs
description: "SocketNotifs is a Dart plugin for Flutter applications that facilitates easy WebSocket connections for notifications"
version: 0.1.8
homepage: https://github.com/yajatkaul/SocketNotifs

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.socketnotifs
        pluginClass: SocketnotifsPlugin
      ios:
        pluginClass: SocketnotifsPlugin
